[package]
name = "epac-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.63", optional = true }
cfg-if = "1.0.0"
find_folder = { version = "0.3.0", optional = true }
piston_window = { version = "0.124.0", optional = true }
tracing = { version = "0.1.36", optional = true }

[features]
default = ["anyhow", "tracing"]
anyhow = ["dep:anyhow"]
tracing = ["dep:tracing"]
piston_cacher = ["dep:piston_window", "dep:find_folder"]